blueprint:
  name: TadoOffset
  description: >
    Cambia il valore di offset tramite un sensore esterno.
    Calcola l'offset tenendo conto dell'offset corrente della valvola e applica la modifica solo se:
      - la differenza tra sensore esterno e sensore Tado supera la tolleranza della modalità
      - è passato almeno il tempo minimo dall'ultimo cambio (input_datetime passato)
      - il nuovo offset (arrotondato a 0.1°C) è diverso dall'offset corrente (arrotondato)
      - l'applicazione dell'offset potrebbe influire sul comportamento della valvola (es. cambiare lo stato on/off)
    Nota: l'offset ha precisione 0.1°C (arrotondamento).
  domain: automation

  input:
    ValvolaRiferimento:
      name: Valvola Tado di riferimento
      description: Entità climate della testa Tado
      selector:
        entity:
          domain: climate
    TadoTemperature:
      name: Sensore di temperatura Tado
      description: Sensore che riporta la temperatura rilevata dalla testa
      selector:
        entity:
          domain: sensor
    ExternalTemperaure:
      name: Sensore di temperartura Esterno
      description: Sensore di temperatura esterno usato come riferimento
      selector:
        entity:
          domain: sensor
    UltimoCambioOffset:
      name: date input che tiene in memoria l'ultimo cambio offset
      description: input_datetime usato per tenere traccia dell'ultimo cambio per questa valvola
      selector:
        entity:
          domain: input_datetime
    Contatore:
      name: Contatore che incrementa ad ogni cambio offset.
      selector:
        entity:
          domain: counter
    TolleranzaHomeHeating:
      name: Valore tolleranza temperatura in Home - Heating
      default: 0.2
      selector:
        number:
          min: 0
          max: 2
          step: 0.1
          unit_of_measurement: "°C"
    TolleranzaHomeOffIdle:
      name: Valore tolleranza temperatura in Home - Off / Idle
      default: 0.4
      selector:
        number:
          min: 0
          max: 2
          step: 0.1
          unit_of_measurement: "°C"
    TolleranzaAway:
      name: Valore tolleranza temperatura in Away
      default: 0.5
      selector:
        number:
          min: 0
          max: 2
          step: 0.1
          unit_of_measurement: "°C"
    MinTimeHomeHeating:
      name: MinTime Home - Heating (secondi)
      description: Intervallo minimo (in secondi) tra due cambi offset in modalità Home+Heating
      default: 300
      selector:
        number:
          min: 0
          max: 60000
          unit_of_measurement: secondi
    MinTimeHomeOffIdle:
      name: MinTime Home - Off / Idle (secondi)
      description: Intervallo minimo (in secondi) tra due cambi offset in modalità Home Off/Idle
      default: 900
      selector:
        number:
          min: 0
          max: 60000
          unit_of_measurement: secondi
    MinTimeAway:
      name: MinTime Away (secondi)
      description: Intervallo minimo (in secondi) tra due cambi offset in modalità Away
      default: 1800
      selector:
        number:
          min: 0
          max: 60000
          unit_of_measurement: secondi
    # epsilon interno non necessario perché usiamo arrotondamento a 0.1°C come scelto;
    # manteniamo comunque un valore di sicurezza per il wait_template
    wait_epsilon:
      name: Soglia per considerare l'offset applicato (°C)
      description: Usata dal wait_template per verificare che l'attributo raggiunga il valore richiesto (piccola soglia)
      default: 0.05
      selector:
        number:
          min: 0.01
          max: 0.2
          step: 0.01
          unit_of_measurement: "°C"

# TRIGGER: manteniamo tutti e tre i trigger come richiesto dall'utente.
# Aggiungiamo un breve debounce (for 10s) per evitare ri-entrate durante aggiornamenti rapidi.
trigger:
  - platform: state
    entity_id: !input ValvolaRiferimento
    for: "00:00:10"
  - platform: state
    entity_id: !input TadoTemperature
    for: "00:00:10"
  - platform: state
    entity_id: !input ExternalTemperaure
    for: "00:00:10"

condition: []

action:
  - variables:
      # INPUTS
      TadoValve: !input ValvolaRiferimento
      TadoTemperatureSensor: !input TadoTemperature
      ExternalSenors: !input ExternalTemperaure
      last_offset_change_variables: !input UltimoCambioOffset
      Counter: !input Contatore
      tollerance_home_heating: !input TolleranzaHomeHeating
      tollerance_home_offidle: !input TolleranzaHomeOffIdle
      tollerance_away: !input TolleranzaAway
      min_time_between_adjust_home_heating: !input MinTimeHomeHeating
      min_time_between_adjust_home_offidle: !input MinTimeHomeOffIdle
      min_time_between_adjust_away: !input MinTimeAway
      wait_eps: !input wait_epsilon

      # STATO CORRENTE: leggiamo gli attributi e gli stati utili
      # last_offset_change è la stringa dell'entity input_datetime (es. "2025-11-18 20:36:15")
      last_offset_change: "{{ states(last_offset_change_variables) }}"
      # offset corrente come float (potrebbe essere negativo)
      last_offset_raw: "{{ state_attr(TadoValve, 'offset_celsius') | default(0.0) | float }}"
      # arrotondato a 1 decimale per confronti (scelta A)
      last_offset: "{{ (state_attr(TadoValve, 'offset_celsius') | default(0.0) | float) | round(1) }}"
      # temperatura mostrata dal sensore Tado (incluso effetto offset)
      tado_disp_raw: "{{ states(TadoTemperatureSensor) | float(0) }}"
      tado_disp: "{{ (states(TadoTemperatureSensor) | float(0)) | round(1) }}"
      # valore del sensore esterno
      external_val_raw: "{{ states(ExternalSenors) | float(0) }}"
      external_val: "{{ (states(ExternalSenors) | float(0)) | round(1) }}"
      # temperatura target impostata sulla valvola
      target_temperature: "{{ state_attr(TadoValve, 'temperature') | float(0) }}"
      # hvac_action e preset_mode correnti
      current_hvac_action: "{{ state_attr(TadoValve, 'hvac_action') | string }}"
      current_preset_mode: "{{ state_attr(TadoValve, 'preset_mode') | string }}"

      # ricavo la modalità semplificata (HHe = home heating, HOI = home off/idle, A = away)
      mode: >-
        {% if (current_preset_mode == 'home') and (current_hvac_action == 'heating') %}
          HHe
        {% elif (current_preset_mode == 'home') and (current_hvac_action != 'heating') %}
          HOI
        {% elif (current_preset_mode == 'away') %}
          A
        {% else %}
          ND
        {% endif %}

      # tolleranza in funzione della modalità (valori configurabili via input)
      tollerance: >-
        {% if (current_preset_mode == 'home') and (current_hvac_action == 'heating') %}
          {{ tollerance_home_heating }}
        {% elif (current_preset_mode == 'home') and (current_hvac_action != 'heating') %}
          {{ tollerance_home_offidle }}
        {% elif (current_preset_mode == 'away') %}
          {{ tollerance_away }}
        {% else %}
          1.0
        {% endif %}

      # min_time in secondi in funzione della modalità
      min_time_between_adjust: >-
        {% if (current_preset_mode == 'home') and (current_hvac_action == 'heating') %}
          {{ min_time_between_adjust_home_heating }}
        {% elif (current_preset_mode == 'home') and (current_hvac_action != 'heating') %}
          {{ min_time_between_adjust_home_offidle }}
        {% elif (current_preset_mode == 'away') %}
          {{ min_time_between_adjust_away }}
        {% else %}
          1.0
        {% endif %}

      # SECONDI dall'ultimo cambiamento: usiamo l'entity UltimoCambioOffset passato al blueprint
      SecLastadjust: >-
        {{ ((as_timestamp(now()) - as_timestamp(states(last_offset_change_variables))) | int) }}

      # CALCOLO DELL'OFFSET: teniamo conto dell'offset corrente secondo la tua logica:
      # O_new = O_curr + (External - Tado_disp)
      # Usiamo i valori raw per il calcolo e poi arrotondiamo a 1 decimale (precisione 0.1°C)
      raw_offset_calc: >-
        {{ (last_offset_raw + (external_val_raw - tado_disp_raw)) }}
      # arrotondamento a 0.1°C come scelto (A)
      offset: "{{ (raw_offset_calc | float) | round(1) }}"

      # clamp (manteniamo i limiti che usavi)
      offset_clamped: >-
        {% set v = offset | float %}
        {% if v > 10.0 %} 10.0
        {% elif v < -9.9 %} -9.9
        {% else %} {{ v | round(1) }}
        {% endif %}

      # nuova temperatura che la valvola vedrebbe dopo l'applicazione dell'offset:
      # T_disp_new = T_disp - O_curr + O_new
      new_displayed_temp: >-
        {{ (tado_disp_raw - last_offset_raw + offset_clamped | float) | round(1) }}

      # flag se l'applicazione dell'offset cambierebbe la relazione rispetto al target
      # (utile per decidere se il cambiamento influenzerà on/off del riscaldamento)
      significant_state_change: >-
        {% set curr_lt = (tado_disp_raw < target_temperature) %}
        {% set new_lt = ((tado_disp_raw - last_offset_raw + offset_clamped | float) < target_temperature) %}
        {{ curr_lt != new_lt }}

      # confronto sugli offset arrotondati a 0.1 (scelta A): procediamo solo se diversi
      offsets_differ: >-
        {{ ( (last_offset | float) != (offset_clamped | float) ) }}

  # Log diagnostico sintetico (disattiva se troppo verboso)
  - service: logbook.log
    data:
      name: "TadoOffset — debug"
      message: >
        valve={{ TadoValve }}; mode={{ mode }}; hvac={{ current_hvac_action }}; preset={{ current_preset_mode }};
        tado={{ tado_disp }}; external={{ external_val }}; diff={{ (external_val_raw - tado_disp_raw) | round(2) }};
        tol={{ tollerance }}; last_offset={{ last_offset }}; new_offset={{ offset_clamped }};
        new_disp={{ new_displayed_temp }}; target={{ target_temperature }};
        SecLastadjust={{ SecLastadjust }}; min_time={{ min_time_between_adjust }};
        offsets_differ={{ offsets_differ }}; significant_state_change={{ significant_state_change }}
      entity_id: "{{ TadoValve }}"
    enabled: false

  # CONDIZIONI PRIMA DI ESEGUIRE LA CHIAMATA AL SERVIZIO TADO:
  - condition: and
    conditions:
      # i sensori devono essere numerici
      - "{{ is_number(states(ExternalSenors)) }}"
      - "{{ is_number(states(TadoTemperatureSensor)) }}"
      # Non siamo in modalità away (come richiesto in precedenza)
      - "{{ state_attr(TadoValve, 'preset_mode') != 'away' }}"
      # differenza esterno - tado deve superare la tolleranza (in funzione della modalità)
      - >-
        {{ ((external_val_raw - tado_disp_raw) | abs) > (tollerance | float) }}
      # è passato almeno min_time dall'ultimo change
      - "{{ SecLastadjust > min_time_between_adjust }}"
      # l'offset arrotondato a 0.1 deve essere diverso dall'attuale arrotondato a 0.1
      - "{{ offsets_differ }}"
      # l'applicazione deve avere potenziale impatto sul funzionamento della valvola
      - "{{ significant_state_change }}"

  # SE TUTTE LE CONDIZIONI SONO VERE -> applichiamo l'offset
  - service: tado.set_climate_temperature_offset
    data:
      entity_id: "{{ TadoValve }}"
      offset: "{{ offset_clamped }}"
    enabled: true

  # Aspettiamo fino a 120s che l'attributo offset_celsius si avvicini al valore richiesto
  # Usiamo una soglia small (wait_eps) per tollerare arrotondamenti e ritardi.
  - wait_template: >-
      {{ ((state_attr(TadoValve, 'offset_celsius') | float(0) - offset_clamped | float(0)) | abs) < (wait_eps | float(0)) }}
    timeout: "00:02:00"
    continue_on_timeout: true

  # Aggiorniamo sempre l'input_datetime ultimo cambio (SCELTA ii: aggiornare comunque)
  # Questo evita retry immediati e preserva batteria; eventuale fallimento è loggato.
  - service: input_datetime.set_datetime
    target:
      entity_id: "{{ last_offset_change_variables }}"
    data:
      date_time: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"

  # Log finale: indichiamo se il valore è stato effettivamente applicato o no
  - service: logbook.log
    data:
      name: "TadoOffset — result"
      message: >
        Valve={{ TadoValve }}; requested_offset={{ offset_clamped }}; applied_offset={{ state_attr(TadoValve, 'offset_celsius') | default('n/a') }};
        achieved={{ ( (state_attr(TadoValve, 'offset_celsius') | float(0) - offset_clamped | float(0)) | abs ) < (wait_eps | float(0)) }};
        new_displayed={{ new_displayed_temp }};
        SecLastadjust_before_update={{ SecLastadjust }}
      entity_id: "{{ TadoValve }}"
    enabled: true

  # Incrementiamo il contatore per tracciare quante volte abbiamo tentato/applicato (a tua scelta)
  - service: counter.increment
    target:
      entity_id: "{{ Counter }}"

mode: single
max: 1
