# Scopo:
#   Automazione per regolare l'offset di una testina Tado in base a un sensore di temperatura esterno.
#   Progettata per ridurre cambi non necessari e preservare batteria limitando le modifiche solo quando necessario.
# Note rapide:
#   - Precisione offset: 0.1 °C (arrotondamento)
#   - Attende fino a 120s la conferma dell'attributo offset_celsius dopo il set
#   - Registra una riga CSV su file per facilità di analisi (import in Excel)
#   - Richiede la presenza di input_datetime e counter per ogni valvola gestita
blueprint:
  name: TadoOffset
  description: >
    Regola l'offset della valvola Tado in base a un sensore esterno.
  domain: automation

  input:
    ValvolaRiferimento:
      name: Valvola Tado di riferimento
      selector:
        entity:
          domain: climate
    TadoTemperature:
      name: Sensore di temperatura Tado
      selector:
        entity:
          domain: sensor
    ExternalTemperaure:
      name: Sensore di temperatura esterno
      selector:
        entity:
          domain: sensor
    UltimoCambioOffset:
      name: input_datetime che memorizza l'ultimo cambio offset
      selector:
        entity:
          domain: input_datetime
    Contatore:
      name: Contatore che incrementa ad ogni tentativo/applicazione offset
      selector:
        entity:
          domain: counter
    TolleranzaHomeHeating:
      name: Tolleranza Home - Heating (°C)
      default: 0.2
      selector:
        number:
          min: 0
          max: 2
          step: 0.1
          unit_of_measurement: "°C"
    TolleranzaHomeOffIdle:
      name: Tolleranza Home - Off/Idle (°C)
      default: 0.4
      selector:
        number:
          min: 0
          max: 2
          step: 0.1
          unit_of_measurement: "°C"
    TolleranzaAway:
      name: Tolleranza Away (°C)
      default: 0.5
      selector:
        number:
          min: 0
          max: 2
          step: 0.1
          unit_of_measurement: "°C"
    MinTimeHomeHeating:
      name: MinTime Home - Heating (secondi)
      default: 300
      selector:
        number:
          min: 0
          max: 60000
          unit_of_measurement: secondi
    MinTimeHomeOffIdle:
      name: MinTime Home - Off/Idle (secondi)
      default: 900
      selector:
        number:
          min: 0
          max: 60000
          unit_of_measurement: secondi
    MinTimeAway:
      name: MinTime Away (secondi)
      default: 1800
      selector:
        number:
          min: 0
          max: 60000
          unit_of_measurement: secondi
    wait_epsilon:
      name: Soglia wait (°C)
      description: Soglia usata per considerare l'offset applicato dal device
      default: 0.05
      selector:
        number:
          min: 0.01
          max: 0.2
          step: 0.01
          unit_of_measurement: "°C"

trigger:
  - platform: state
    entity_id: !input ValvolaRiferimento
    for: "00:00:10"
  - platform: state
    entity_id: !input TadoTemperature
    for: "00:00:10"
  - platform: state
    entity_id: !input ExternalTemperaure
    for: "00:00:10"

condition: []

action:
  - variables:
      # entità in ingresso
      TadoValve: !input ValvolaRiferimento
      TadoTemperatureSensor: !input TadoTemperature
      ExternalSenors: !input ExternalTemperaure
      last_offset_change_variables: !input UltimoCambioOffset
      Counter: !input Contatore

      # parametri
      tollerance_home_heating: !input TolleranzaHomeHeating
      tollerance_home_offidle: !input TolleranzaHomeOffIdle
      tollerance_away: !input TolleranzaAway
      min_time_between_adjust_home_heating: !input MinTimeHomeHeating
      min_time_between_adjust_home_offidle: !input MinTimeHomeOffIdle
      min_time_between_adjust_away: !input MinTimeAway
      wait_eps: !input wait_epsilon

      # stato corrente (conversioni sicure)
      last_offset_change: "{{ states(last_offset_change_variables) | default('') }}"
      last_offset_raw: "{{ state_attr(TadoValve, 'offset_celsius') | float(0) }}"
      last_offset: "{{ (state_attr(TadoValve, 'offset_celsius') | float(0)) | round(1) }}"
      tado_disp_raw: "{{ states(TadoTemperatureSensor) | float(0) }}"
      tado_disp: "{{ (states(TadoTemperatureSensor) | float(0)) | round(1) }}"
      external_val_raw: "{{ states(ExternalSenors) | float(0) }}"
      external_val: "{{ (states(ExternalSenors) | float(0)) | round(1) }}"

      # Temperatura target (attribute 'temperature')
      target_raw: "{{ state_attr(TadoValve, 'temperature') }}"
      target_present: "{{ (target_raw is not none) }}"
      target_temperature: >-
        {% if target_raw is not none %}
          {{ (target_raw | float(0)) }}
        {% else %}
          none
        {% endif %}

      current_hvac_action: "{{ state_attr(TadoValve, 'hvac_action') | default('') | string }}"
      current_preset_mode: "{{ state_attr(TadoValve, 'preset_mode') | default('') | string }}"

      # Calcolo della modalità
      mode: >-
        {% if (current_preset_mode == 'home') and (current_hvac_action == 'heating') %}
          HHe
        {% elif (current_preset_mode == 'home') and (current_hvac_action != 'heating') %}
          HOI
        {% elif (current_preset_mode == 'away') %}
          A
        {% else %}
          ND
        {% endif %}

      # tolleranza e min_time in base alla modalità
      tollerance: >-
        {% if mode == 'HHe' %} {{ tollerance_home_heating }}
        {% elif mode == 'HOI' %} {{ tollerance_home_offidle }}
        {% elif mode == 'A' %} {{ tollerance_away }}
        {% else %} 1.0 {% endif %}

      min_time_between_adjust: >-
        {% if mode == 'HHe' %} {{ min_time_between_adjust_home_heating }}
        {% elif mode == 'HOI' %} {{ min_time_between_adjust_home_offidle }}
        {% elif mode == 'A' %} {{ min_time_between_adjust_away }}
        {% else %} 1.0 {% endif %}

      # secondi dall'ultimo cambiamento
      SecLastadjust: >-
        {{ ((as_timestamp(now()) - (as_timestamp(states(last_offset_change_variables)) or 0)) | int) }}

      # calcolo offset: O_new = O_curr + (External - Tado_disp)
      raw_offset_calc: >-
        {{ (last_offset_raw + (external_val_raw - tado_disp_raw)) }}
      offset: "{{ (raw_offset_calc | float) | round(1) }}"
      offset_clamped: >-
        {% set v = offset | float %}
        {% if v > 10.0 %} 10.0
        {% elif v < -9.9 %} -9.9
        {% else %} {{ v | round(1) }}
        {% endif %}

      # nuova temperatura percepita dopo l'applicazione
      new_displayed_temp: >-
        {{ (tado_disp_raw - last_offset_raw + offset_clamped | float) | round(1) }}

      # significant_state_change:
      # - se temperatura target presente: verifica impatto rispetto al target (passaggio da ON->OFF e viceversa)
      # - se temperatura target assente: fallback conservativo (diff >= 2 * tollerance)
      significant_state_change: >-
        {% if target_present %}
          {% set curr_req = (tado_disp_raw < (target_temperature | float(0))) %}
          {% set new_req = ((tado_disp_raw - last_offset_raw + offset_clamped | float) < (target_temperature | float(0))) %}
          {{ curr_req != new_req }}
        {% else %}
          {{ ((external_val_raw - tado_disp_raw) | abs) >= ((tollerance | float) * 2) }}
        {% endif %}

      offsets_differ: >-
        {{ ( (last_offset | float) != (offset_clamped | float) ) }}

  - action: shell_command.tado_dir
    data: {}
  - action: shell_command.tado_fil
    metadata: {}
    data: {}    
  - service: shell_command.tado_log
    data:
      text: >    
           {{ states[TadoValve].name }};
           {{ mode }};
           {{ state_attr(TadoValve, 'preset_mode') }};
           {{ state_attr(TadoValve, 'hvac_action') }};
           {{ (states(TadoTemperatureSensor) | float(0)) | round(1) }};
           {{ (states(ExternalSenors) | float(0)) | round(1) }};
           {{ (((states(TadoTemperatureSensor) | float(0)) | round(1)) - ((states(ExternalSenors) | float(0)) | round(1))) | round(1) }};
           {{ (tollerance | float(0)) | round(1) }};
           {{ (state_attr(TadoValve, 'offset_celsius') | float(0)) }};
           {{ (offset | float(0)) | round(1) }};
           {{ (((states(TadoTemperatureSensor) | float(0)) | round(1)) - (state_attr(TadoValve, 'offset_celsius') | float(0) | round(1)) + (offset | float(0))) | round(1) }};
           {{ (state_attr(TadoValve, 'temperature') | default('') ) }};
           {{ states(last_offset_change_variables) }};
           {{ now() }};
           {{ SecLastadjust }};
           {{ min_time_between_adjust }};
           {{ (is_number(states(ExternalSenors))) }};
           {{ (is_number(states(TadoTemperatureSensor))) }};
           {{ ((state_attr(TadoValve, 'offset_celsius') | float(0) | round(1)) != (offset | float(0) | round(1))) }};
           {{ ((((states(ExternalSenors) | float(0) | round(1)) - (states(TadoTemperatureSensor) | float(0) | round(1))) | abs) > (tollerance | float(0))) }};
           {{ (SecLastadjust > min_time_between_adjust) }};
           {{ (state_attr(TadoValve, 'preset_mode') != "away") }};
           {{ (state_attr(TadoValve, 'hvac_action') != "off") }};
           {{ ((states(TadoTemperatureSensor) | float(0) | round(1)) - (state_attr(TadoValve, 'offset_celsius') | float(0) | round(1)) + (offset | float(0))) < (state_attr(TadoValve, 'temperature') | float(0)) }};
           {{ (is_number(states(ExternalSenors))) and (is_number(states(TadoTemperatureSensor))) and ((state_attr(TadoValve, 'offset_celsius') | float(0) | round(1)) != (offset | float(0) | round(1))) and ((((states(ExternalSenors) | float(0) | round(1)) - (states(TadoTemperatureSensor) | float(0) | round(1))) | abs) > (tollerance | float(0))) and (SecLastadjust > min_time_between_adjust) and (state_attr(TadoValve, 'preset_mode') != "away") and (state_attr(TadoValve, 'hvac_action') != "off") and (((states(TadoTemperatureSensor) | float(0) | round(1)) - (state_attr(TadoValve, 'offset_celsius') | float(0) | round(1)) + (offset | float(0))) < (state_attr(TadoValve, 'temperature') | float(0)) ) }};

  # CONDIZIONI PRIMA DI ESEGUIRE LA CHIAMATA AL SERVIZIO TADO:
  - condition: and
    conditions:
      - "{{ is_number(states(ExternalSenors)) }}"
      - "{{ is_number(states(TadoTemperatureSensor)) }}"
      - "{{ state_attr(TadoValve, 'preset_mode') != 'away' }}"
      - >-
        {{ ((external_val_raw - tado_disp_raw) | abs) > (tollerance | float) }}
      - "{{ SecLastadjust > min_time_between_adjust }}"
      - "{{ offsets_differ }}"
      - "{{ significant_state_change }}"

  # APPLICA L'OFFSET (se condizione passata)
  - service: tado.set_climate_temperature_offset
    data:
      entity_id: "{{ TadoValve }}"
      offset: "{{ offset_clamped }}"
    enabled: true

  # WAIT fino a 120s per conferma offset (tolleranza small)
  - wait_template: >-
      {{ ((state_attr(TadoValve, 'offset_celsius') | float(0) - offset_clamped | float(0)) | abs) < (wait_eps | float(0)) }}
    timeout: "00:02:00"
    continue_on_timeout: true

  # aggiorniamo l'input_datetime ultimo cambio
  - service: input_datetime.set_datetime
    target:
      entity_id: "{{ last_offset_change_variables }}"
    data:
      date_time: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"

  # log risultato (logbook CSV-friendly)
  - service: logbook.log
    data:
      name: "{{ states[TadoValve].name }}"
      message: >
        is currently {{ state_attr(TadoValve, 'hvac_action') }} with temp {{ states(TadoTemperatureSensor) }} but room is {{ states( ExternalSenors) }}
        changing offset from {{ last_offset }} to {{ offset }} - ({{ mode }};{{ tollerance }};{{ min_time_between_adjust }};{{ SecLastadjust }};{{ offset }})
      entity_id: |
        {{ TadoValve }}
      domain: climate
    enabled: true

  # Incrementa il contatore per tracciare quante volte abbiamo tentato/applicato
  - service: counter.increment
    target:
      entity_id: "{{ Counter }}"

mode: single
