# Blueprint: TadoOffset
# Scopo:
#   Automazione per regolare l'offset di una testina Tado in base a un sensore esterno.
# Note:
#   - Precisione offset: 0.1 °C (arrotondamento)
#   - Attende fino a 120s la conferma dell'attributo offset_celsius dopo il set
#   - Registra una riga CSV su file per facilità di analisi (import in Excel)
blueprint:
  name: TadoOffset
  description: >
    Regola l'offset della valvola Tado in base a un sensore esterno.
  domain: automation

  input:
    ValvolaRiferimento:
      name: Valvola Tado di riferimento
      selector:
        entity:
          domain: climate
    TadoTemperature:
      name: Sensore di temperatura Tado
      selector:
        entity:
          domain: sensor
    ExternalSensor:
      name: Sensore di temperatura esterno
      selector:
        entity:
          domain: sensor
    UltimoCambioOffset:
      name: input_datetime che memorizza l'ultimo cambio offset
      selector:
        entity:
          domain: input_datetime
    Contatore:
      name: Contatore che incrementa ad ogni tentativo/applicazione offset
      selector:
        entity:
          domain: counter
    Tolleranza:
      name: Tolleranza tra temperatura rilevata dalla valvola e il sensore esterno (°C)
      default: 0.2
      selector:
        number:
          min: 0
          max: 2
          step: 0.1
          unit_of_measurement: "°C"
    MinTime:
      name: Tempo Minimo tra un cambio offset ed un'altro
      default: 300
      selector:
        number:
          min: 0
          max: 60000
          unit_of_measurement: secondi
    wait_epsilon:
      name: Soglia wait (°C)
      description: Soglia usata per considerare l'offset applicato dal device
      default: 0.05
      selector:
        number:
          min: 0.01
          max: 0.2
          step: 0.01
          unit_of_measurement: "°C"

trigger:
  - platform: state
    entity_id: !input ValvolaRiferimento
    for: "00:00:10"
  - platform: state
    entity_id: !input TadoTemperature
    for: "00:00:10"
  - platform: state
    entity_id: !input ExternalSensor
    for: "00:00:10"

condition: []

action:
  - variables:
      # entità in ingresso
      TadoValve: !input ValvolaRiferimento
      TadoTemperatureSensor: !input TadoTemperature
      ExternalSenors: !input ExternalSensor
      last_offset_change_variables: !input UltimoCambioOffset
      Counter: !input Contatore

      # parametri
      tollerance: !input Tolleranza
      min_time_between_adjust: !input MinTime
      wait_eps: !input wait_epsilon

      # stato corrente (conversioni sicure)
      last_offset_change: "{{ states(last_offset_change_variables) | default('') }}"
      last_offset_raw: "{{ state_attr(TadoValve, 'offset_celsius') | float(0) }}"
      last_offset: "{{ (state_attr(TadoValve, 'offset_celsius') | float(0)) | round(1) }}"
      tado_disp_raw: "{{ states(TadoTemperatureSensor) | float(0) }}"
      tado_disp: "{{ (states(TadoTemperatureSensor) | float(0)) | round(1) }}"
      external_val_raw: "{{ states(ExternalSenors) | float(0) }}"
      external_val: "{{ (states(ExternalSenors) | float(0)) | round(1) }}"

      # Temperatura target (attribute 'temperature')
      target_raw: "{{ state_attr(TadoValve, 'temperature') }}"
      target_present: "{{ (target_raw is not none) }}"
      target_temperature: >-
        {% if target_raw is not none %}
          {{ (target_raw | float(0)) }}
        {% else %}
          none
        {% endif %}

      current_hvac_action: "{{ state_attr(TadoValve, 'hvac_action') | default('') | string }}"
      current_preset_mode: "{{ state_attr(TadoValve, 'preset_mode') | default('') | string }}"


      # secondi dall'ultimo cambiamento
      SecLastadjust: >-
        {{ ((as_timestamp(now()) - (as_timestamp(states(last_offset_change_variables)) or 0)) | int) }}

      # calcolo offset: O_new = O_curr + (External - Tado_disp)
      raw_offset_calc: >-
        {{ (last_offset_raw + (external_val_raw - tado_disp_raw)) }}
      offset: "{{ (raw_offset_calc | float) | round(1) }}"
      offset_clamped: >-
        {% set v = offset | float %}
        {% if v > 10.0 %} 10.0
        {% elif v < -9.9 %} -9.9
        {% else %} {{ v | round(1) }}
        {% endif %}

      # nuova temperatura percepita dopo l'applicazione
      new_displayed_temp: >-
        {{ (tado_disp_raw - last_offset_raw + offset_clamped | float) | round(1) }}

      # significant_state_change: VALUTATO SOLO SE target è presente
      # -> True quando curr_req != new_req (cambio ON<->OFF)
      significant_state_change: >-
        {% if target_present %}
          {% set curr_req = (tado_disp_raw < (target_temperature | float(0))) %}
          {% set new_req = ((tado_disp_raw - last_offset_raw + offset_clamped | float) < (target_temperature | float(0))) %}
          {{ curr_req != new_req }}
        {% else %}
          False
        {% endif %}

      offsets_differ: >-
        {{ ( (last_offset | float) != (offset_clamped | float) ) }}

      # variabili booleane per log e condizione
      c1_sensor_is_number: "{{ is_number(states(ExternalSenors)) }}"
      c2_tado_is_number: "{{ is_number(states(TadoTemperatureSensor)) }}"
      c3_offset_diff: "{{ offsets_differ }}"
      c4_diff_gt_tolerance: >-
        {{ (((external_val_raw - tado_disp_raw) | abs) > (tollerance | float(0))) }}
      c5_seclast_gt_min: "{{ SecLastadjust > min_time_between_adjust }}"
      c6_preset_is_home: "{{ current_preset_mode == 'home' }}"
      c7_significant_state_change: "{{ significant_state_change }}"

      # all_conditions = espressione che deve essere vera per ESEGUIRE il set
      # Requisiti:
      #  - preset_mode == 'home'
      #  - sensori numerici
      #  - offset differisce
      #  - tempo dall'ultimo cambio > min_time
      #  - significant_state_change == True (cambio ON<->OFF)
      all_conditions: >-
        {{ c1_sensor_is_number and c2_tado_is_number and c3_offset_diff and c4_diff_gt_tolerance and c5_seclast_gt_min and c6_preset_is_home and c7_significant_state_change }}
      
      
      # --- costruzione riga CSV (semplificata, ordinata e completa con c6/c7) ---
      csv_log: >-
        {{ [
          (states[TadoValve].name | replace(';','') | default('')),
          (current_preset_mode | default('')),
          (current_hvac_action | default('')),
          (tado_disp_raw | float(0) | round(1)),
          (external_val_raw | float(0) | round(1)),
          ((tado_disp_raw | float(0) | round(1) - external_val_raw | float(0) | round(1)) | round(1)),
          (tollerance | float(0) | round(1)),
          (last_offset_raw | float(0)),
          (offset | float(0) | round(1)),
          (new_displayed_temp | float(0) | round(1)),
          (state_attr(TadoValve, 'temperature') | default('')),
          (states(last_offset_change_variables) | default('')),
          (now().strftime('%Y-%m-%d %H:%M:%S')),
          (SecLastadjust | default(0)),
          (min_time_between_adjust | default(0)),
          (c1_sensor_is_number),
          (c2_tado_is_number),
          (c3_offset_diff),
          (c4_diff_gt_tolerance),
          (c5_seclast_gt_min),
          (c6_preset_is_home),
          (c7_significant_state_change),
          (all_conditions)
        ] | map('string') | join(';') }}

  # LOG su file (CSV) - crea directory, crea file giornaliero con header (se necessario) e appende la riga
  - service: shell_command.tado_dir
  - service: shell_command.tado_fil
  - service: shell_command.tado_log
    data:
      text: "{{ csv_log }}"

  # CONDIZIONI PRIMA DI ESEGUIRE LA CHIAMATA AL SERVIZIO TADO:
  - condition: and
    conditions:
      - "{{ c1_sensor_is_number }}"
      - "{{ c2_tado_is_number }}"
      - "{{ c3_offset_diff }}"
      - "{{ c4_diff_gt_tolerance }}"
      - "{{ c5_seclast_gt_min }}"
      - "{{ c6_preset_is_home }}"
      - "{{ c7_significant_state_change }}"

  # APPLICA L'OFFSET (se condizione passata)
  - service: tado.set_climate_temperature_offset
    data:
      entity_id: "{{ TadoValve }}"
      offset: "{{ offset_clamped }}"
    enabled: true

  # WAIT fino a 240s per conferma offset (tolleranza small)
  - wait_template: >-
      {{ ((state_attr(TadoValve, 'offset_celsius') | float(0) - offset_clamped | float(0)) | abs) < (wait_eps | float(0)) }}
    timeout: "00:04:00"
    continue_on_timeout: true

  # aggiorniamo sempre l'input_datetime ultimo cambio (corretto: chiave 'datetime')
  - service: input_datetime.set_datetime
    target:
      entity_id: "{{ last_offset_change_variables }}"
    data:
      datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"

  # log risultato (logbook CSV-friendly) - testo aggiornato in italiano
  - service: logbook.log
    data:
      name: "{{ states[TadoValve].name }}"
      message: >-
        Valvola {{ states[TadoValve].name }} è in modalità {{ state_attr(TadoValve, 'hvac_action') }}
        con temperatura {{ states(TadoTemperatureSensor) }}°C ({{ (tado_disp_raw - last_offset_raw) | round(1) }}°C) ma il sensore esterno rileva {{ states(ExternalSenors) }}°C.
        Cambio l'offset da {{ last_offset }}°C a {{ offset_clamped }}°C.
      entity_id: "{{ TadoValve }}"
      domain: climate
    enabled: true

  # Incrementa il contatore per tracciare quante volte abbiamo tentato/applicato
  - service: counter.increment
    target:
      entity_id: "{{ Counter }}"

mode: single
